apiVersion: batch/v1
kind: Job
metadata:
  name: nexoraai-training-job
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: us-central1-docker.pkg.dev/mlops-506205/nexoraai-mlops/trainer:v6
      restartPolicy: Never
  backoffLimit: 1
